In [2]:
import numpy as np
import subprocess

In [31]:
#A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float64)
# symmetric np.array
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]], dtype=np.float64)
print(A)

[[1. 2. 3.]
 [2. 4. 5.]
 [3. 5. 6.]]


In [32]:
!rm input_data.txt
with open('input_data.txt','a') as f:
    f.write(f"{A.shape[0]} {A.shape[1]}\n")
    np.savetxt(f,A, newline="\n")
!cat input_data.txt

3 3
1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
2.000000000000000000e+00 4.000000000000000000e+00 5.000000000000000000e+00
3.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00


In [33]:
result = subprocess.run(['g++', '-std=c++11', 'powerMethod.cpp', '-o', 'powerMethod'], capture_output=True)
print(result.stdout.decode())
print(result.stderr.decode())

if result.returncode == 0:
    print('Compilation successful')
else:
    print('Compilation failed')



Compilation successful


In [34]:
niter = 1000
tol = 1e-6
subprocess.run(['./powerMethod', 'input_data.txt', 'values.txt', 'vectors.txt', str(niter), str(tol)])

Matrix A:
1 2 3
2 4 5
3 5 6


CompletedProcess(args=['./powerMethod', 'input_data.txt', 'values.txt', 'vectors.txt', '1000', '1e-06'], returncode=0)

In [35]:
# read values.txt and vectors.txt as np arrays:
vectors = np.loadtxt('vectors.txt')
values = np.loadtxt('values.txt')
vectors, values

(array([[ 0.327985,  0.73694 , -0.590872],
        [ 0.591009,  0.32803 ,  0.737037],
        [ 0.736976, -0.59103 , -0.328095]]),
 array([11.3448  , -0.515729,  0.170915]))

In [36]:
A, vectors

(array([[1., 2., 3.],
        [2., 4., 5.],
        [3., 5., 6.]]),
 array([[ 0.327985,  0.73694 , -0.590872],
        [ 0.591009,  0.32803 ,  0.737037],
        [ 0.736976, -0.59103 , -0.328095]]))

In [37]:
# Check that A@v = lambda@v:
for i in range(len(values)):
    print(A @ vectors[:,i])
    print(values[i] * vectors[:,i])
    print()

[3.720931 6.704886 8.360856]
[3.72092423 6.7048789  8.36084532]

[-0.38009 -0.16915  0.30479]
[-0.38006133 -0.16917458  0.30481131]

[-0.101083  0.125929 -0.056001]
[-0.10098889  0.12597068 -0.05607636]



In [ ]:
# Test con autovalores y autovector conocidos


In [ ]:
# Test con matrices con autovalores repetidos


In [ ]:
#Analizar la convergencia en casos con autovalores muy cercanos.

In [ ]:
 # Comparar los errores contra Numpy